/**
 * Build a Markdown export of an RCA report and trigger a browser download.
 */
export function downloadReportMarkdown(report) {
  const md = renderReportMarkdown(report);
  const blob = new Blob([md], { type: "text/markdown;charset=utf-8" });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = `${report.incident_id}-rca.md`;
  document.body.appendChild(a);
  a.click();
  a.remove();
  URL.revokeObjectURL(url);
}

export function renderReportMarkdown(r) {
  const lines = [];
  const toolLog = Array.isArray(r.tool_log) ? r.tool_log : [];
  const totalCalls = toolLog.length;
  const blockedCalls = toolLog.filter((t) => t.approved === false).length;
  const accessCounts = toolLog.reduce((acc, t) => {
    const k = t.access || "unknown";
    acc[k] = (acc[k] || 0) + 1;
    return acc;
  }, {});
  const accessSummary = Object.entries(accessCounts)
    .map(([k, v]) => `${v} ${k}`)
    .join(", ");

  lines.push(`# OpsLens RCA Report: ${r.incident_id}`);
  lines.push("");
  lines.push(`**Asset:** ${r.asset_id}`);
  lines.push(`**Started:** ${r.started_at}`);
  lines.push(`**Completed:** ${r.completed_at}`);
  lines.push(`**Overall confidence:** ${(r.confidence * 100).toFixed(0)}%`);
  lines.push(
    `**MCP Gateway:** ${totalCalls} tool calls audited, ${blockedCalls} blocked` +
      (accessSummary ? ` (${accessSummary})` : "")
  );
  lines.push("");
  lines.push(`## Safety Verdict: ${r.safety?.status || "N/A"}`);
  if (r.safety?.blocking_concerns?.length) {
    lines.push("**Blocking concerns:**");
    r.safety.blocking_concerns.forEach((b) => lines.push(`- ${b}`));
  }
  if (r.safety?.cited_sops?.length) {
    lines.push(`**Cited SOPs:** ${r.safety.cited_sops.join(", ")}`);
  }
  lines.push("");
  lines.push("## Top Hypothesis");
  lines.push(`**${r.top_hypothesis.summary}** (likelihood ${r.top_hypothesis.likelihood})`);
  if (r.top_hypothesis.evidence?.length) {
    r.top_hypothesis.evidence.forEach((e) => lines.push(`- ${e}`));
  }
  if (r.alternative_hypotheses?.length) {
    lines.push("");
    lines.push("## Alternative Hypotheses");
    r.alternative_hypotheses.forEach((h) =>
      lines.push(`- (p=${h.likelihood}) ${h.summary}`)
    );
  }
  if (r.known_unknowns?.length) {
    lines.push("");
    lines.push("## Known Unknowns");
    r.known_unknowns.forEach((u) => lines.push(`- ${u}`));
  }
  lines.push("");
  lines.push("## Human Review Checklist");
  r.human_review_checklist?.forEach((c) =>
    lines.push(`- [ ] **[${c.severity}]** ${c.label} (_${c.rationale}_)`)
  );
  if (r.capa_draft) {
    lines.push("");
    lines.push("## CAPA Draft");
    lines.push(`> ${r.capa_draft.draft_status}`);
    lines.push("");
    lines.push("**Corrective actions:**");
    r.capa_draft.corrective_actions.forEach((a) => lines.push(`- ${a}`));
    lines.push("");
    lines.push("**Preventive actions:**");
    r.capa_draft.preventive_actions.forEach((a) => lines.push(`- ${a}`));
    lines.push("");
    lines.push(`**Approvals required:** ${r.capa_draft.approvals_required.join(", ")}`);
  }
  if (toolLog.length) {
    lines.push("");
    lines.push("## MCP Gateway Audit Trail");
    lines.push("");
    lines.push(
      "Every tool call below was inspected by the deterministic policy layer " +
        "(`safety_gateway`) before execution. The gateway cannot be overridden by an LLM."
    );
    lines.push("");
    lines.push("| # | Agent | Tool | Risk | Access | Args | Duration | Verdict |");
    lines.push("|---|---|---|---|---|---|---|---|");
    toolLog.forEach((t, i) => {
      const argsRaw = JSON.stringify(t.arguments ?? {});
      const args = mdEscape(truncate(argsRaw, 70));
      const dur = t.duration_ms != null ? `${Number(t.duration_ms).toFixed(2)} ms` : "n/a";
      const verdict = t.approved
        ? "approved"
        : `BLOCKED: ${mdEscape(t.rejection_reason || "policy")}`;
      lines.push(
        `| ${i + 1} | ${t.requested_by || "n/a"} | \`${t.tool}\` | ${t.risk_level || "n/a"}` +
          ` | ${t.access || "n/a"} | \`${args}\` | ${dur} | ${verdict} |`
      );
    });
  }
  lines.push("");
  lines.push("---");
  lines.push("_Generated by OpsLens MCP. AI output. Engineer is the final decision-maker._");
  return lines.join("\n");
}

function truncate(s, n) {
  if (s == null) return "";
  return s.length > n ? s.slice(0, n - 1) + "…" : s;
}

function mdEscape(s) {
  // Pipe and backtick break Markdown tables; newlines collapse cells.
  return String(s)
    .replace(/\|/g, "\\|")
    .replace(/`/g, "\\`")
    .replace(/\r?\n/g, " ");
}
